version: '3'
services:
    php:
        build:
            dockerfile: ./.Docker/php/DockerFile
            args:
                WWWGROUP: '${WWWGROUP}'
        volumes:
            - './docs:/var/www'
            - /var/www/.Docker
            - /var/app/ssl
        networks:
            - portfolio_network
    
    nginx:
        build:
          context: ./.Docker/nginx
        volumes_from:
          - php
        volumes:
          - ./.Docker/ssl:/etc/nginx/ssl
        ports:
          - "80:80"
          - "443:443"
        networks:
          - portfolio_network
        depends_on:
          - php
networks:
    portfolio_network:
        driver: bridge
volumes:
    docker_mysql:
        driver: local
